### ISSUE TITLE
collect_results.py needs RM option

### ISSUE THREAD

**Issue by hringbauer** [MPI-EVA-Archaeogenetics/helper_scripts#12]
The script to collect the autorun_eager results `collect_results.py`  (in [Autorun_multiqc_stats_collect](https://github.com/MPI-EVA-Archaeogenetics/helper_scripts/tree/main/Autorun_multiqc_stats_collect))  needs a flag for the analysis_ type RM. 

It currently only allows for the types SG, TF, and RP.

It is a highly useful script for producing summary tables, and it would be really useful to have it for RM data as well.

@TCLamnidis

**Comment by TCLamnidis** [comment]
See #11 
😄
